services:
  imagine-sandbox-template-tanstack-start:
    image: appwrite/imagine-sandbox-template-tanstack-start:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9123:9123
    env_file: .env
